import markdown
from xhtml2pdf import pisa
from src.vector_engine import VectorEngine
from src.llm_judge import GeminiJudge

def save_to_pdf(markdown_text, filename="Similarity_Report.pdf"):
    """Converts Markdown verdict to a styled PDF."""
    print(f"\n📄 Generating PDF Report: {filename}...")
    
    # 1. Convert Markdown to HTML (enabling tables)
    html_content = markdown.markdown(markdown_text, extensions=['tables', 'fenced_code'])
    
    # 2. Add CSS for clean printing
    full_html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Helvetica, sans-serif; font-size: 11pt; line-height: 1.5; }}
            h1, h2, h3 {{ color: #2E4053; margin-top: 20px; }}
            table {{ 
                border-collapse: collapse; 
                width: 100%; 
                margin-top: 15px; 
                margin-bottom: 15px; 
                font-size: 10pt;
            }}
            th, td {{ border: 1px solid #ddd; padding: 10px; text-align: left; }}
            th {{ background-color: #f2f2f2; font-weight: bold; }}
            tr:nth-child(even) {{ background-color: #f9f9f9; }}
            .verdict-box {{
                border: 2px solid #333;
                padding: 15px;
                background-color: #fafafa;
                margin-top: 20px;
            }}
        </style>
    </head>
    <body>
        <h1 style="text-align: center;">Project Similarity Report</h1>
        <hr>
        {html_content}
        <br>
        <hr>
        <p style="text-align: center; font-size: 9pt; color: #777;">Generated by TrueProject AI Judge</p>
    </body>
    </html>
    """

    # 3. Write PDF
    try:
        with open(filename, "wb") as pdf_file:
            pisa_status = pisa.CreatePDF(full_html, dest=pdf_file)
        
        if pisa_status.err:
            print("❌ Error generating PDF.")
        else:
            print(f"✅ PDF saved successfully to: {filename}")
            
    except Exception as e:
        print(f"❌ Failed to save PDF: {e}")

def check_proposal(title, synopsis):
    print(f"\n🔎 Analyzing Proposal: '{title}'...")

    # 1. Initialize Engines
    try:
        engine = VectorEngine()
        if not engine.load_index():
            print("❌ Error: Index files not found. Please run 'run_indexer.py' first.")
            return
        
        judge = GeminiJudge()
    except Exception as e:
        print(f"❌ Initialization Error: {e}")
        return

    # 2. Vector Search
    print("   ...Searching database for similarities...")
    matches = engine.search(title, synopsis)
    
    print(f"\n--- 🤖 FOUND {len(matches)} POTENTIAL MATCHES ---")
    for i, m in enumerate(matches):
        print(f"   Match #{i+1}: {m['name']} (Similarity: {m['similarity']}%)")

    # 3. AI Verdict
    print("\n⚖️  Sending evidence to AI Judge (DeepSeek)...")
    verdict = judge.get_verdict({"title": title, "synopsis": synopsis}, matches)
    
    # Print to Console
    print("\n" + "="*50)
    print("📢 FINAL REPORT")
    print("="*50)
    print(verdict)
    print("="*50)
    
    # 4. Save to PDF
    save_to_pdf(verdict, f"Report_{title.replace(' ', '_')}.pdf")

if __name__ == "__main__":
    # --- TEST INPUT ---
    new_title = "Smart Traffic Control System"
    new_synopsis = "A system that uses cameras and AI to change traffic lights based on vehicle density."
    
    check_proposal(new_title, new_synopsis)